global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:80']  # Endereço do serviço app (seu servidor web)

  - job_name: 'mysql'
    static_configs:
      - targets: ['db:3306']  # Endereço do serviço db (seu banco de dados)
